source 'https://rubygems.org'
gem 'rails', '4.1.4'
gem 'pg', '~> 0.17.1'
gem 'bcrypt', '~> 3.1.7'
gem 'foundation-rails', '~> 5.3'
gem 'font-awesome-rails', '~> 4.1'
gem 'devise', '~> 3.3'
gem 'omniauth-github', '~> 1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'high_voltage', '~> 2.2.1'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
