# Generated secret_key_base with rake secret
# Get Facebook keys at https://developers.facebook.com/apps/
# Get Twitter keys at https://apps.twitter.com/
development:
  devise_secret_key: ____________
  secret_key_base: ____________

  github_id: ____________
  github_secret: ____________

test:
  devise_secret_key: ____________
  secret_key_base: ____________

  github_id: ____________
  github_secret: ____________

production:
  devise_secret_key: ____________
  secret_key_base: ____________

  github_id: ____________
  github_secret: ____________
